name: Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        configuration: [debug, release]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1.6.0
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet msbuild -noLogo -m -p:Configuration=${{ matrix.configuration }} -bl:artifacts/log/build.binlog
      - name: Test
        run: dotnet test -noLogo --no-restore --blame-hang --blame-hang-timeout 300s --blame-crash -d artifacts/TestResults/tests.log -r artifacts/TestResults --collect:"XPlat Code Coverage"
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}_${{ matrix.configuration }}
          path: |
            ./artifacts/bin/**/*
            ./artifacts/log/**/*
            ./artifacts/TestResults/**/*
          if-no-files-found: error